export const environment = {
    production: true,
    environment: 'prod',
    protocol  : 'https://',
    host      : 'xxx.xxx.com',
    api_path  : '/api-mt4/',
    dbhost: '47.99.133.60',
    dbport: 3306,
    database: 'das',
    dbusername: 'das',
    dbpassword: 'Das_Admin@202011',
    fu_dbhost: '172.22.139.205',
    fu_dbport: 3306,
    fu_database: 'trans_record',
    fu_dbusername: 'trsreader',
    fu_dbpassword: 'trsrOK',
};
